apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:5.0.17
          ports:
            - containerPort: 27017
          env:
          - name: MONGODB_ROOT_PASSWORD
            value: root 
          - name: MONGODB_REPLICA_SET_MODE
            value: primary 
          - name: MONGODB_REPLICA_SET_KEY
            value: replicasetkey123
          - name: MONGODB_DATABASE
            value: "homebroker"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: trader-api
          image: perescassiano/trader-api:v1
          ports:
          - containerPort: 3000
          env:
          - name: DATABASE_URL
            value: mongodb://root:root@mongodb:27017/homebroker?directConnection=true&authSource=admin
          - name: KAFKA_ENDPOINT
            value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 3000
    # nodePort: 30000
  # type: NodePort
  type: LoadBalancer


