name: CI-CD
on:
  push:
    branches: ["main","master"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from code base
        uses: actions/checkout@v3.6.0
      - name: DockerHub auth
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push docker images
        uses: docker/build-push-action@v4.1.1
      - name: Step 3
        run: echo "Push image to docker repo - Dockerhub"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Step 1
        run: echo "Download code base"
      - name: Step 2
        run: echo "AWS authentication"
      - name: Step 3
        run: echo "Deploy microservices to EKS"
