name: CI-CD
on:
  push:
    branches: ["main","master"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Download code base"
      - name: Step 2
        run: echo "Create microservices images"
      - name: Step 3
        run: echo "Push image to docker repo - Dockerhub"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Step 1
        run: echo "Download code base"
      - name: Step 2
        run: echo "AWS authentication"
      - name: Step 3
        run: echo "Deploy microservices to EKS"
